const resources = [
  { type:'Algorithm', icon:'braces', title:'MAPPO-UAV', domain:'Multi-Agent Reinforcement Learning', description:'面向多无人系统协同编队与决策控制的开源实现。', tags:['MAPPO','PyTorch','ROS2'], stars:'1.2k', downloads:'8.6k', updated:'2 days ago' },
  { type:'Model', icon:'box', title:'YOLO-World', domain:'Computer Vision', description:'开放词汇目标检测模型，适配复杂开放场景。', tags:['PyTorch','Detection'], stars:'4.8k', downloads:'20k', updated:'3 days ago' },
  { type:'Model', icon:'brain-circuit', title:'DeepSeek-R1-Distill', domain:'Large Language Models', description:'面向推理任务的轻量化开放语言模型系列。', tags:['LLM','Reasoning'], stars:'3.4k', downloads:'18k', updated:'1 day ago' },
  { type:'Project', icon:'folder-git-2', title:'TimeSeries-Transformer', domain:'Forecasting', description:'用于多变量时序预测的 Transformer 基准工程。', tags:['Transformer','Forecasting'], stars:'860', downloads:'4.2k', updated:'5 days ago' },
];
const fields = [
  ['brain-circuit','AI & Deep Learning','Models, training methods and AI systems','2,438','#eef2ff','#4f46e5'],['scan-eye','Computer Vision','Perception, detection and visual understanding','1,826','#ecfeff','#0e7490'],['bot','Robotics','Embodied intelligence and autonomous systems','964','#ecfdf5','#047857'],['plane','Unmanned Systems','Aerial, marine and ground unmanned platforms','748','#fff7ed','#c2410c'],['rotate-3d','Reinforcement Learning','Decision making and policy optimization','632','#f5f3ff','#7e22ce'],['network','Multi-Agent Systems','Cooperation, competition and distributed intelligence','418','#eff6ff','#2563eb'],['chart-no-axes-combined','Intelligent Optimization','Metaheuristics and complex optimization','562','#fefce8','#a16207'],['zap','Energy & Smart Grid','Energy forecasting, dispatch and control','384','#f0fdfa','#0f766e'],['messages-square','Large Language Models','Language, reasoning and agentic systems','1,214','#fdf2f8','#be185d'],['chart-spline','Time-Series Forecasting','Temporal modeling and uncertainty analysis','527','#f8fafc','#475569'],['sliders-horizontal','Control Systems','Modeling, control and verification','498','#f1f5f9','#334155'],['calculator','Scientific Computing','Numerical methods and reproducible science','306','#f8fafc','#334155']
];
const models = [['YOLO-UAV-Detection','Object Detection','PyTorch','36M','12.8k','Apache 2.0','scan-eye'],['TimeSeries Transformer','Forecasting','PyTorch','18M','8.2k','MIT','chart-spline'],['MAPPO Policy Suite','Reinforcement Learning','PyTorch','9M','6.4k','MIT','bot'],['GridLoad Foundation','Energy Forecasting','JAX','112M','4.1k','Apache 2.0','zap']];
const datasets = [['UAV Object Detection Dataset','高分辨率航拍目标检测与多场景标注基准。','Object Detection','18.4 GB','24,800 images','8.2k'],['Wind & PV Forecast Dataset','多地区风电与光伏出力时序预测数据集。','Time-Series Forecasting','2.1 GB','CSV · 8 years','5.6k'],['Multi-Agent Navigation Bench','多智能体协同导航、避障与通信仿真数据。','Reinforcement Learning','6.8 GB','126 scenarios','3.9k']];
const projects = [['Multi-UAV Formation Control','以 MAPPO 为核心的多无人机协同编队控制与仿真验证。','MAPPO','ROS2','Gazebo','PyTorch','1.4k'],['Open Vision Inspection','面向工业视觉质检的端侧模型、数据集和部署方案。','YOLO','ONNX','Edge AI','Python','980'],['Smart Grid Forecast Lab','覆盖预测、优化调度与不确定性量化的研究工程。','Transformer','JAX','Energy','MATLAB','760']];
const demos = [['Multi-UAV Formation Control','Multi-Agent · MAPPO','03:24','https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1300&q=85'],['Visual Navigation in the Wild','Computer Vision · YOLO + SLAM','02:18','https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1100&q=85'],['Time-Series Forecasting','Energy Systems · CNN-LSTM-Attention','01:52','https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1100&q=85']];
const collections = [['Deep Learning Starter Pack','从基础模型、训练方法到可复现实验的入门专题。','12 Models','8 Datasets','21 Tutorials'],['Multi-Agent Reinforcement Learning','围绕协同决策、策略学习和仿真验证的完整资源路径。','9 Models','5 Datasets','38 Papers'],['Intelligent Optimization Algorithms','连接经典元启发式算法与现代智能优化实践。','16 Algorithms','11 Tutorials','24 Papers']];
const contributors = [['KS','Kai Shen','28 Resources · 1.2k Stars'],['LW','Lena Wu','22 Resources · 860 Stars'],['XZ','Xia Zhang','19 Resources · 740 Stars'],['MR','Ming Rao','17 Resources · 620 Stars'],['YC','Yuan Chen','15 Resources · 510 Stars'],['HY','Han Yu','13 Resources · 486 Stars']];

const icon = (name) => `<i data-lucide="${name}"></i>`;
document.querySelector('#trendingGrid').innerHTML = resources.map(r => `<article class="resource-card"><div class="resource-top"><span class="type-badge">${icon(r.icon)}${r.type}</span><button title="收藏">${icon('star')}</button></div><h3>${r.title}</h3><span class="domain">${r.domain}</span><p class="description">${r.description}</p><div class="tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="metadata"><span>${icon('star')}${r.stars}</span><span>${icon('download')}${r.downloads}</span><span>${icon('clock-3')}${r.updated}</span></div></article>`).join('');
document.querySelector('#fieldGrid').innerHTML = fields.map(([iconName,title,desc,count,bg,color]) => `<article class="field-card"><span class="field-icon" style="background:${bg};color:${color}">${icon(iconName)}</span><h3>${title}</h3><p>${desc}</p><small>${count} resources</small></article>`).join('');
document.querySelector('#modelGrid').innerHTML = models.map(([title,task,framework,params,downloads,license,iconName]) => `<article class="model-card"><div class="model-title"><span>${icon(iconName)}</span><div><h3>${title}</h3><p>${task}</p></div></div><div class="tags"><span>${framework}</span><span>${license}</span></div><div class="model-specs"><div><small>Parameters</small><b>${params}</b></div><div><small>Downloads</small><b>↓ ${downloads}</b></div></div></article>`).join('');
document.querySelector('#datasetGrid').innerHTML = datasets.map(([title,desc,task,size,files,downloads]) => `<article class="dataset-card"><div class="dataset-heading"><span>${icon('database')}</span><div><h3>${title}</h3><small>${task}</small></div></div><p>${desc}</p><div class="dataset-stats"><span>Size<b>${size}</b></span><span>Files<b>${files}</b></span><span>Downloads<b>↓ ${downloads}</b></span></div></article>`).join('');
document.querySelector('#projectGrid').innerHTML = projects.map(([title,desc,...meta]) => `<article class="project-card"><div class="project-heading"><span>${icon('folder-git-2')}</span><div class="mini-avatars"><i></i><i></i><i></i></div></div><h3>${title}</h3><p>${desc}</p><div class="project-resources">${meta.slice(0,4).map(t=>`<span>${icon('check-circle-2')}${t}</span>`).join('')}</div><div class="project-footer"><span>${icon('star')} ${meta[4]} stars</span><span>Code · Data · Demo</span></div></article>`).join('');
document.querySelector('#demoGrid').innerHTML = demos.map(([title,field,duration,image],index) => `<article class="demo-card" data-demo="${title}"><img src="${image}" alt="${title} demo preview"/><span class="play-button">${icon('play')}</span><div class="demo-content"><small>${field} · ${duration}</small><h3>${title}</h3><p>Open interactive research demo</p></div></article>`).join('');
document.querySelector('#collectionGrid').innerHTML = collections.map(([title,desc,...metrics]) => `<article class="collection-card"><div class="collection-top"><span>${icon('layers-3')}</span>${icon('arrow-up-right')}</div><h3>${title}</h3><p>${desc}</p><div class="collection-metrics">${metrics.map(m=>`<span>${m}</span>`).join('')}</div></article>`).join('');
document.querySelector('#contributorGrid').innerHTML = contributors.map(([avatar,name,stats]) => `<article class="contributor"><span class="avatar">${avatar}</span><span><b>${name}</b><small>${stats}</small></span></article>`).join('');

const searchDialog = document.querySelector('#searchDialog'); const commandInput = document.querySelector('#commandInput'); const commandResults = document.querySelector('#commandResults');
let searchItems = [...resources.map(r=>({type:r.type,title:r.title,meta:r.domain,icon:r.icon})),...models.map(m=>({type:'Model',title:m[0],meta:m[1],icon:m[6]})),...projects.map(p=>({type:'Project',title:p[0],meta:'Featured project',icon:'folder-git-2'})),...datasets.map(d=>({type:'Dataset',title:d[0],meta:d[2],icon:'database'}))];
function renderSearch(query=''){const matched=searchItems.filter(x=>`${x.title} ${x.meta} ${x.type}`.toLowerCase().includes(query.toLowerCase())).slice(0,7);commandResults.innerHTML=matched.length?`<div class="result-label">${query?'SEARCH RESULTS':'SUGGESTED RESOURCES'}</div>${matched.map(x=>`<button class="search-result"><span>${icon(x.icon)}</span><b>${x.title}</b><small>${x.type} · ${x.meta}</small></button>`).join('')}`:'<div class="result-label">No matching resource</div>';lucide.createIcons()}
function openSearch(){renderSearch();searchDialog.showModal();setTimeout(()=>commandInput.focus(),50)}
document.querySelectorAll('#openSearch,#heroSearch').forEach(b=>b.addEventListener('click',openSearch));commandInput.addEventListener('input',e=>renderSearch(e.target.value));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'&&searchDialog.open)searchDialog.close()});
const publishDialog=document.querySelector('#publishDialog');document.querySelectorAll('#openPublish,#heroPublish,#communityPublish').forEach(b=>b.addEventListener('click',()=>publishDialog.showModal()));
const demoDialog=document.querySelector('#demoDialog');document.addEventListener('click',e=>{const card=e.target.closest('[data-demo]');if(card){document.querySelector('#demoTitle').textContent=card.dataset.demo;demoDialog.showModal()}const close=e.target.closest('[data-close]');if(close)document.querySelector('#'+close.dataset.close).close()});
document.querySelector('#themeToggle').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.querySelector('#themeToggle').innerHTML=icon(document.documentElement.dataset.theme==='dark'?'sun':'moon');lucide.createIcons()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.style.opacity='1';entry.target.style.transform='translateY(0)';observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.section,.feature-section,.community').forEach(el=>{el.style.opacity='0';el.style.transform='translateY(12px)';el.style.transition='opacity .35s ease,transform .35s ease';observer.observe(el)});
lucide.createIcons();

// Replace homepage mock cards with the V1 API when the backend is available.
const apiIcon = type => ({model:'box',dataset:'database',algorithm:'braces',project:'folder-git-2',paper:'file-text',demo:'play',tutorial:'book-open'}[type] || 'sparkles');
const compactNumber = value => { const n = Number(value || 0); return n >= 1000 ? `${(n / 1000).toFixed(n >= 10000 ? 0 : 1).replace('.0','')}k` : String(n); };
const apiEscape = value => String(value ?? '').replace(/[&<>'\"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;', '"':'&quot;'}[char]));
const apiResources = item => ({ type:item.resource_type.charAt(0).toUpperCase()+item.resource_type.slice(1), icon:apiIcon(item.resource_type), title:apiEscape(item.title), domain:apiEscape(item.tags?.[0]?.name || item.resource_type), description:apiEscape(item.description), tags:(item.tags || []).slice(0,4).map(tag=>apiEscape(tag.name)), stars:compactNumber(item.stars), downloads:compactNumber(item.downloads), updated:'V1 API', raw:item });
function applyApiResources(items){
  if(!Array.isArray(items) || !items.length) return;
  const apiCards = items.map(apiResources);
  const renderResource = r => `<article class="resource-card"><div class="resource-top"><span class="type-badge">${icon(r.icon)}${r.type}</span><button title="收藏">${icon('star')}</button></div><h3>${r.title}</h3><span class="domain">${r.domain}</span><p class="description">${r.description}</p><div class="tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="metadata"><span>${icon('star')}${r.stars}</span><span>${icon('download')}${r.downloads}</span><span>${icon('clock-3')}${r.updated}</span></div></article>`;
  document.querySelector('#trendingGrid').innerHTML = apiCards.slice(0,4).map(renderResource).join('');
  const modelItems = apiCards.filter(r=>r.raw.resource_type==='model').slice(0,4);
  if(modelItems.length) document.querySelector('#modelGrid').innerHTML = modelItems.map(r=>`<article class="model-card"><div class="model-title"><span>${icon(r.icon)}</span><div><h3>${r.title}</h3><p>${apiEscape(r.raw.details?.model?.task || r.raw.details?.task || r.domain)}</p></div></div><div class="tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}<span>${apiEscape(r.raw.license)}</span></div><div class="model-specs"><div><small>Parameters</small><b>${apiEscape(r.raw.details?.model?.parameters || r.raw.details?.parameters || '—')}</b></div><div><small>Downloads</small><b>↓ ${r.downloads}</b></div></div></article>`).join('');
  const datasetItems = apiCards.filter(r=>r.raw.resource_type==='dataset').slice(0,3);
  if(datasetItems.length) document.querySelector('#datasetGrid').innerHTML = datasetItems.map(r=>`<article class="dataset-card"><div class="dataset-heading"><span>${icon('database')}</span><div><h3>${r.title}</h3><small>${apiEscape(r.raw.details?.dataset?.format || r.domain)}</small></div></div><p>${r.description}</p><div class="dataset-stats"><span>Size<b>${apiEscape(r.raw.details?.dataset?.size || '—')}</b></span><span>Format<b>${apiEscape(r.raw.details?.dataset?.format || '—')}</b></span><span>Downloads<b>↓ ${r.downloads}</b></span></div></article>`).join('');
  const projectItems = apiCards.filter(r=>r.raw.resource_type==='project').slice(0,3);
  if(projectItems.length) document.querySelector('#projectGrid').innerHTML = projectItems.map(r=>`<article class="project-card"><div class="project-heading"><span>${icon('folder-git-2')}</span><div class="mini-avatars"><i></i><i></i><i></i></div></div><h3>${r.title}</h3><p>${r.description}</p><div class="project-resources">${r.tags.map(t=>`<span>${icon('check-circle-2')}${t}</span>`).join('')}</div><div class="project-footer"><span>${icon('star')} ${r.stars} stars</span><span>Code · Data · Demo</span></div></article>`).join('');
  searchItems = apiCards.map(r=>({type:r.type,title:r.title,meta:r.domain,icon:r.icon}));
  lucide.createIcons();
}
fetch('/api/resources?limit=100').then(response=>response.ok ? response.json() : []).then(applyApiResources).catch(()=>{});
